# Generated by Django 5.0 on 2024-09-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'زیرمجموعه', 'verbose_name_plural': 'ساختمان هایه زیرمحموعه'},
        ),
        migrations.AlterField(
            model_name='companies',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_company', to='vendors.company'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_comany', to='vendors.company'),
        ),
    ]
