# Generated by Django 5.0 on 2024-09-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_ex',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_pd',
        ),
    ]
